from .agents import MESSAGE_CATEGORIZER_AGENT, MESSAGE_WRITER_AGENT
from .tasks import CATEGORIZER_TASK, WRITER_TASK

MESSAGE_CATEGORIZER_PROMPT = f"{MESSAGE_CATEGORIZER_AGENT} \n {CATEGORIZER_TASK}"
MESSAGE_WRITER_PROMPT = f"{MESSAGE_WRITER_AGENT}\n\n{WRITER_TASK}"